const users = [
  {
    id: 1,
    name: "Mahammad Ali",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01789652394",
    serialNumber: "65",
    image: "https://i.ibb.co/DCHGygB/c0b153a0b253.jpg",
  },
  {
    id: 2,
    name: "Md. Subbir Islam",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01762867328",
    serialNumber: "66",
    image: "https://i.ibb.co/8DzJ3Gn/Sabbir.png",
  },
  {
    id: 3,
    name: "Md. Rojob Ali",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01752256776",
    serialNumber: "67",
    image: "https://i.ibb.co/986jSND/Rojob.png",
  },
];

const candidate = [
  {
    id: 1,
    name: "Mahammad Ali",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01789652394",
    serialNumber: "65",
    image: "https://i.ibb.co/DCHGygB/c0b153a0b253.jpg",
    post: "President",
    numberOfVote: 0,
  },
  {
    id: 2,
    name: "Md. Subbir Islam",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01762867328",
    serialNumber: "66",
    image: "https://i.ibb.co/8DzJ3Gn/Sabbir.png",
    post: "President",
    numberOfVote: 0,
  },
  {
    id: 3,
    name: "Md. Rojob Ali",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01752256776",
    serialNumber: "67",
    image: "https://i.ibb.co/986jSND/Rojob.png",
    post: "President",
    numberOfVote: 0,
  },
  {
    id: 4,
    name: "Mahammad Ali",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01789652394",
    serialNumber: "65",
    image: "https://i.ibb.co/DCHGygB/c0b153a0b253.jpg",
    post: "President",
    numberOfVote: 0,
  },
  {
    id: 5,
    name: "Md. Subbir Islam",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01762867328",
    serialNumber: "66",
    image: "https://i.ibb.co/8DzJ3Gn/Sabbir.png",
    post: "President",
    numberOfVote: 0,
  },
  {
    id: 6,
    name: "Md. Rojob Ali",
    designation: "Office assistant cum-computer typist",
    section: "Accounts",
    mobile: "01752256776",
    serialNumber: "67",
    image: "https://i.ibb.co/986jSND/Rojob.png",
    post: "President",
    numberOfVote: 0,
  },
];
export { users, candidate };
